/**
 * Fetch Google Fonts locally into public/fonts/.
 *
 * Pulls woff2 files + an @font-face CSS snippet via the community
 * google-webfonts-helper API (https://gwfh.mranftl.com/) so we don't have to
 * scrape https://fonts.googleapis.com/css at runtime. Idempotent: skips
 * already-present files.
 *
 * Usage: pnpm tsx scripts/fetch-fonts.ts
 */
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const OUT = join(process.cwd(), 'public', 'fonts');

interface FontSpec {
  family: string; // gwfh slug ("bangers", "rajdhani")
  label: string; // pretty name for CSS ("Bangers", "Rajdhani")
  subsets: string; // e.g. "latin"
  variants: string; // comma-separated, e.g. "regular,500,600,700"
}

const FONTS: FontSpec[] = [
  { family: 'bangers', label: 'Bangers', subsets: 'latin', variants: 'regular' },
  { family: 'rajdhani', label: 'Rajdhani', subsets: 'latin', variants: 'regular,500,600,700' },
];

interface GwfhVariant {
  fontFamily: string;
  fontStyle: string;
  fontWeight: string;
  woff2: string;
  woff: string;
  ttf?: string;
  local?: string[];
}

interface GwfhResponse {
  id: string;
  family: string;
  variants: GwfhVariant[];
  subsets: string[];
  category: string;
  version: string;
  lastModified: string;
}

async function fetchFamily(spec: FontSpec): Promise<string> {
  const url =
    `https://gwfh.mranftl.com/api/fonts/${spec.family}` +
    `?subsets=${spec.subsets}&variants=${spec.variants}&formats=woff2`;
  const resp = await fetch(url);
  if (!resp.ok) {
    throw new Error(`[fetch-fonts] ${spec.family}: ${resp.status} ${resp.statusText}`);
  }
  const data = (await resp.json()) as GwfhResponse;

  const cssChunks: string[] = [];
  for (const v of data.variants) {
    const weight = v.fontWeight;
    const filename = `${spec.family}-${weight}.woff2`;
    const localPath = join(OUT, filename);
    if (!existsSync(localPath)) {
      const fontResp = await fetch(v.woff2);
      if (!fontResp.ok) {
        throw new Error(`[fetch-fonts] ${v.woff2}: ${fontResp.status}`);
      }
      const bytes = new Uint8Array(await fontResp.arrayBuffer());
      writeFileSync(localPath, bytes);
    } else {
    }

    cssChunks.push(
      `@font-face {
  font-family: '${spec.label}';
  font-style: ${v.fontStyle};
  font-weight: ${weight};
  font-display: swap;
  src: url('./${filename}') format('woff2');
}`,
    );
  }

  return cssChunks.join('\n\n');
}

async function main(): Promise<void> {
  if (!existsSync(OUT)) mkdirSync(OUT, { recursive: true });

  const allCss: string[] = [];
  for (const spec of FONTS) {
    const css = await fetchFamily(spec);
    allCss.push(css);
  }

  const cssPath = join(OUT, 'fonts.css');
  const header = `/*
 * Auto-generated by scripts/fetch-fonts.ts.
 * Do not hand-edit — run \`pnpm fetch:fonts\` to regenerate.
 */

`;
  writeFileSync(cssPath, `${header + allCss.join('\n\n')}\n`);
}

void main();
